import { StringEnum } from "@earendil-works/pi-ai";
import type {
  ExtensionAPI,
  ExtensionContext,
} from "@earendil-works/pi-coding-agent";
import { Text } from "@earendil-works/pi-tui";
import { existsSync } from "node:fs";
import { mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { Type } from "typebox";

interface StudyState {
  active: boolean;
  topic: string;
  curriculumPath: string;
  progressPath: string;
  learnerLevel?: "new" | "beginner" | "intermediate" | "advanced" | "unknown";
  assessmentSummary?: string;
  currentModule?: string;
  currentLesson?: string;
  completed: string[];
  nextStep?: string;
  notes: Array<{ at: string; text: string }>;
  updatedAt: string;
}

const ProgressParams = Type.Object({
  action: StringEnum([
    "status",
    "update",
    "complete",
    "note",
    "set_next_step",
    "save",
  ] as const),
  currentModule: Type.Optional(
    Type.String({ description: "Current curriculum module" }),
  ),
  currentLesson: Type.Optional(
    Type.String({ description: "Current lesson or exercise" }),
  ),
  learnerLevel: Type.Optional(
    StringEnum([
      "new",
      "beginner",
      "intermediate",
      "advanced",
      "unknown",
    ] as const),
  ),
  assessmentSummary: Type.Optional(
    Type.String({
      description:
        "Terse, neutral placement notes used only to adapt instruction; avoid biography or identity labels",
    }),
  ),
  completedItem: Type.Optional(
    Type.String({
      description: "A newly completed item, checkpoint, or exercise",
    }),
  ),
  note: Type.Optional(
    Type.String({
      description: "Brief learner progress note or misconception to remember",
    }),
  ),
  nextStep: Type.Optional(
    Type.String({
      description:
        "The next meaningful work session, milestone, or exploration branch for the learner",
    }),
  ),
});

function studyDir(cwd: string): string {
  return join(cwd, ".pi", "study");
}

function statePath(cwd: string): string {
  return join(studyDir(cwd), "study-state.json");
}

function curriculumPath(cwd: string): string {
  return join(studyDir(cwd), "CURRICULUM.md");
}

function progressPath(cwd: string): string {
  return join(studyDir(cwd), "PROGRESS.md");
}

async function readJson<T>(path: string): Promise<T | undefined> {
  try {
    return JSON.parse(await readFile(path, "utf8")) as T;
  } catch {
    return undefined;
  }
}

async function writeText(path: string, content: string): Promise<void> {
  await mkdir(dirname(path), { recursive: true });
  await writeFile(path, content, "utf8");
}

function emptyState(cwd: string, topic = "unspecified topic"): StudyState {
  const now = new Date().toISOString();
  return {
    active: true,
    topic,
    curriculumPath: curriculumPath(cwd),
    progressPath: progressPath(cwd),
    learnerLevel: "unknown",
    completed: [],
    notes: [],
    updatedAt: now,
  };
}

async function loadState(cwd: string): Promise<StudyState | undefined> {
  const state = await readJson<StudyState>(statePath(cwd));
  if (state) {
    delete (state as StudyState & { srs?: unknown }).srs;
    state.completed ??= [];
    state.notes ??= [];
    state.learnerLevel ??= "unknown";
  }
  return state;
}

async function saveState(cwd: string, state: StudyState): Promise<void> {
  state.updatedAt = new Date().toISOString();
  await writeText(statePath(cwd), JSON.stringify(state, null, 2) + "\n");
  await writeProgressMarkdown(state);
}

function curriculumTemplate(topic: string): string {
  return `# Study Curriculum: ${topic}\n\n> Generated by Pi Study Mode. Treat this as a living map, not a rigid syllabus.\n\n## Learning Goal\n\nDescribe what you want to be able to build, understand, or explore with ${topic}.\n\n## Placement / Starting Point\n\nBefore finalizing the plan, ask 3-5 short diagnostic questions to determine the learner's current level, goals, preferred project scale, feedback cadence, and desired pace. Keep placement notes terse and focused on learning needs, not biography. Update this section after checking their answers.\n\n- Placement level: unknown\n- Relevant starting assumptions, kept terse:\n- Current learning needs:\n- Gaps / misconceptions:\n- Time available:\n- Preferred project / practice style:\n- Desired review cadence and pace:\n\n## Exploration Zones\n\n1. Orientation and Tooling\n   - [ ] Set up a comfortable compile/run/test/debug loop\n   - [ ] Read one small real example and map unknowns\n   - [ ] Checkpoint: explain the workflow and choose a first project branch\n2. Core Concepts Through Programs\n   - [ ] Build a medium-sized program that forces the core ideas to appear naturally\n   - [ ] Keep an open questions / discoveries log\n   - [ ] Checkpoint: review code, behavior, and design tradeoffs\n3. Debugging and Revision\n   - [ ] Investigate compiler/runtime errors from the project\n   - [ ] Revise for correctness, clarity, and safety\n   - [ ] Checkpoint: compare before/after versions and name the lesson learned\n4. Applied Project Track\n   - [ ] Choose or design a substantial project milestone\n   - [ ] Work independently for a meaningful stretch\n   - [ ] Review artifact: code, tests, output, design notes, or failing case\n5. Reflection and Resume Points\n   - [ ] Record durable concepts, repeated weak spots, and project decisions as notes\n   - [ ] Save clear stopping points with the next concrete work session\n   - [ ] Decide the next exploration branch or deeper project\n\n## Running Progress\n\n- Current exploration area: TBD\n- Current project / artifact: TBD\n- Next meaningful work session: TBD\n- Open questions: TBD\n\n## Teacher Notes\n\nUse this section for durable observations about misconceptions, strengths, project ideas, review preferences, and questions to revisit.\n`;
}

function progressMarkdown(state: StudyState): string {
  const completed = state.completed.length
    ? state.completed.map((item) => `- [x] ${item}`).join("\n")
    : "- No completed items recorded yet.";
  const notes = state.notes.length
    ? state.notes.map((n) => `- ${n.at}: ${n.text}`).join("\n")
    : "- No notes yet.";
  return `# Study Progress: ${state.topic}\n\n- Active: ${state.active ? "yes" : "no"}\n- Placement level: ${state.learnerLevel ?? "unknown"}\n- Placement notes: ${state.assessmentSummary ?? "TBD"}\n- Current module: ${state.currentModule ?? "TBD"}\n- Current lesson: ${state.currentLesson ?? "TBD"}\n- Next meaningful work session: ${state.nextStep ?? "TBD"}\n- Last updated: ${state.updatedAt}\n\n## Resume Point\n\nTo continue, run \`/study resume\` from this project. The assistant should pick up from the current module/lesson and next meaningful work session above.\n\n## Completed\n\n${completed}\n\n## Notes\n\n${notes}\n\n## Files\n\n- Curriculum: ${state.curriculumPath}\n- State JSON: ${statePath(dirname(dirname(dirname(state.progressPath))))}\n`;
}

async function writeProgressMarkdown(state: StudyState): Promise<void> {
  await writeText(state.progressPath, progressMarkdown(state));
}

async function ensureStudyFiles(
  cwd: string,
  topic: string,
): Promise<StudyState> {
  const dir = studyDir(cwd);
  await mkdir(dir, { recursive: true });
  let state = await loadState(cwd);
  if (!state) state = emptyState(cwd, topic);
  state.active = true;
  state.topic = topic || state.topic;
  state.curriculumPath = curriculumPath(cwd);
  state.progressPath = progressPath(cwd);
  state.completed ??= [];
  state.notes ??= [];
  state.learnerLevel ??= "unknown";

  if (!existsSync(state.curriculumPath)) {
    await writeText(state.curriculumPath, curriculumTemplate(state.topic));
  }
  await saveState(cwd, state);
  return state;
}

function statusLines(state?: StudyState): string[] {
  if (!state)
    return ["Study mode: no curriculum in this cwd. Run /study start <topic>."];
  return [
    `Study mode: ${state.active ? "active" : "paused"}`,
    `Topic: ${state.topic}`,
    `Level: ${state.learnerLevel ?? "unknown"}`,
    `Current: ${state.currentModule ?? "TBD"}${state.currentLesson ? ` / ${state.currentLesson}` : ""}`,
    `Next: ${state.nextStep ?? "TBD"}`,
    `Completed: ${state.completed.length}`,
    `Curriculum: ${state.curriculumPath}`,
    `Progress: ${state.progressPath}`,
  ];
}

function updateUi(ctx: ExtensionContext, state?: StudyState): void {
  if (!ctx.hasUI) return;
  if (!state?.active) {
    ctx.ui.setStatus("study-mode", undefined);
    ctx.ui.setWidget("study-mode", undefined);
    return;
  }
  ctx.ui.setStatus("study-mode", ctx.ui.theme.fg("accent", "📚 study"));
  ctx.ui.setWidget("study-mode", [
    ctx.ui.theme.fg("accent", `📚 ${state.topic}`),
    ctx.ui.theme.fg(
      "muted",
      `Now: ${state.currentModule ?? "TBD"}${state.currentLesson ? ` / ${state.currentLesson}` : ""}`,
    ),
    ctx.ui.theme.fg(
      "muted",
      `Next: ${state.nextStep ?? "Ask the learner for a plan, artifact, or revision"}`,
    ),
    ctx.ui.theme.fg(
      "dim",
      "Use /study pause to stop here; /study resume to continue",
    ),
  ]);
}

function teachingPrompt(state: StudyState): string {
  return `\n\n## PI STUDY MODE ACTIVE\n\nYou are tutoring the user on: ${state.topic}.\n\nPersistent files:\n- Curriculum: ${state.curriculumPath}\n- Progress: ${state.progressPath}\n\nCurrent progress:\n- Placement level: ${state.learnerLevel ?? "unknown"}\n- Placement notes: ${state.assessmentSummary ?? "TBD"} (use only to adapt difficulty; do not repeat or quote to the learner)\n- Exploration area: ${state.currentModule ?? "TBD"}\n- Project / milestone: ${state.currentLesson ?? "TBD"}\n- Next meaningful work session: ${state.nextStep ?? "TBD"}\n- Completed items: ${state.completed.length ? state.completed.join("; ") : "none yet"}
\nMandatory teaching behavior:\n- DO NOT give the learner the finished answer by default. Act as a coach and reviewer, not an answer key.\n- If placement level is unknown, ask 3-5 short diagnostic questions before finalizing the curriculum. Include current goals, relevant starting point, preferred project scale, feedback cadence, desired pace, and only tiny skill checks that help choose a starting point.\n- Adapt the curriculum into an exploratory project map, not a rigid lesson ladder.\n- Prefer medium-sized programs, experiments, design sketches, debugging sessions, and revision cycles over isolated minutia drills.\n- Keep pace brisk and adaptive: once the learner has correctly predicted, implemented, or explained the core idea, advance to the next meaningful concept or integrate it into a larger artifact. Do not add extra micro-drills just because the topic has more edge cases.\n- Teach just enough theory to unblock the current project or exploration branch. Avoid nitpicking trivia unless it affects correctness, safety, debugging, or idiomatic use.\n- Do not repeat the learner's stored background, biography, job history, or assessment summary in normal replies. Use placement notes privately for difficulty calibration, and prefer evidence from the learner's current work over initial background assumptions.\n- Ask for the learner's plan, code, experiment result, design choice, or revision before revealing solutions.\n- Review work at natural checkpoints: say what is solid, identify the highest-impact issues, and suggest one or two meaningful revisions or branches.\n- Use escalating hints before any reveal. If the learner explicitly asks for the answer, first offer one more hint unless they insist.\n- Keep the curriculum and progress current. Use study_update_progress after meaningful progress, artifact completion, review, revision, a new misconception, a saved stopping point, or a new exploration branch.\n- Record durable concepts, repeated weak spots, and useful review observations as normal progress notes.\n- If the curriculum file is missing, too vague, or too lesson-drill oriented, create or improve it before continuing.\n`;
}

export default function studyMode(pi: ExtensionAPI): void {
  let cachedState: StudyState | undefined;

  async function refresh(ctx: ExtensionContext): Promise<void> {
    cachedState = await loadState(ctx.cwd);
    updateUi(ctx, cachedState);
  }

  pi.on("session_start", async (_event, ctx) => refresh(ctx));
  pi.on("session_tree", async (_event, ctx) => refresh(ctx));

  pi.on("before_agent_start", async (event, ctx) => {
    await refresh(ctx);
    if (!cachedState?.active) return;
    return { systemPrompt: event.systemPrompt + teachingPrompt(cachedState) };
  });

  pi.registerCommand("study", {
    description:
      "Study mode: /study start <topic>, resume, pause [note], status, help",
    handler: async (args, ctx) => {
      const [subcommandRaw, ...rest] = args.trim().split(/\s+/).filter(Boolean);
      const subcommand = subcommandRaw ?? "status";
      const argText = rest.join(" ");

      if (subcommand === "help") {
        ctx.ui.notify(
          "/study start <topic> | /study resume | /study pause [note] | /study status | /study help",
          "info",
        );
        return;
      }

      if (subcommand === "start") {
        const topic =
          argText ||
          (ctx.hasUI
            ? await ctx.ui.input("Study topic", "What do you want to learn?")
            : undefined);
        if (!topic) {
          ctx.ui.notify("Study start cancelled: no topic provided.", "warning");
          return;
        }
        cachedState = await ensureStudyFiles(ctx.cwd, topic);
        pi.setSessionName(`Study: ${topic}`);
        updateUi(ctx, cachedState);
        ctx.ui.notify(
          `Study mode started. Curriculum: ${cachedState.curriculumPath}`,
          "info",
        );
        pi.sendUserMessage(
          `Study mode is now active for "${topic}". Before finalizing the curriculum, run a brief placement diagnostic: ask me 3-5 short questions to determine my current level, goals, preferred project scale, feedback cadence, and desired pace. Include only tiny skill checks that help choose a starting project. Ask a compact numbered set, then wait for my answers. After checking my responses, update study progress with learnerLevel and a terse, neutral assessmentSummary focused on learning needs, not biography. Do not repeat that summary back to me in normal replies; use it only to calibrate difficulty. Then tailor ${cachedState.curriculumPath} as an exploratory project map. Record durable concepts and weak spots as notes instead of separate review queues. Remember: do not give me finished answers; coach me through planning, writing, revising, and reviewing medium-sized programs, and move on once I demonstrate the core idea.`,
        );
        return;
      }

      cachedState = await loadState(ctx.cwd);
      if (!cachedState) {
        ctx.ui.notify(
          "No study state here. Run /study start <topic>.",
          "warning",
        );
        return;
      }

      if (subcommand === "status") {
        ctx.ui.notify(statusLines(cachedState).join("\n"), "info");
        return;
      }

      if (subcommand === "pause") {
        if (argText)
          cachedState.notes.push({
            at: new Date().toISOString(),
            text: `Paused: ${argText}`,
          });
        cachedState.active = false;
        await saveState(ctx.cwd, cachedState);
        updateUi(ctx, cachedState);
        ctx.ui.notify(
          `Study mode paused. Resume later with /study resume. Next: ${cachedState.nextStep ?? "TBD"}`,
          "info",
        );
        return;
      }

      if (subcommand === "resume" || subcommand === "continue") {
        cachedState.active = true;
        await saveState(ctx.cwd, cachedState);
        updateUi(ctx, cachedState);
        pi.sendUserMessage(
          `Resume Study Mode for "${cachedState.topic}" from the saved progress. Orient me briefly, then continue from this next meaningful work session: ${cachedState.nextStep ?? "TBD"}. Current area: ${cachedState.currentModule ?? "TBD"}. Current milestone: ${cachedState.currentLesson ?? "TBD"}.`,
        );
        return;
      }

      ctx.ui.notify(
        `Unknown /study command: ${subcommand}. Try /study help.`,
        "warning",
      );
    },
  });

  pi.registerTool({
    name: "study_update_progress",
    label: "Study Progress",
    description:
      "Update or inspect Pi Study Mode progress files. Use this after meaningful learner progress, completed artifacts/reviews, important notes, pace/preferences, or changes to the next exploration step.",
    promptSnippet: "Update or inspect the active study curriculum progress",
    promptGuidelines: [
      "Use study_update_progress whenever Study Mode is active and the learner completes a checkpoint/artifact, shows a misconception, changes exploration area/project, saves a stopping point, or receives a new meaningful work session.",
    ],
    parameters: ProgressParams,
    async execute(_toolCallId, params, _signal, _onUpdate, ctx) {
      let state = await loadState(ctx.cwd);
      if (!state) {
        state = await ensureStudyFiles(ctx.cwd, "unspecified topic");
      }

      if (params.currentModule) state.currentModule = params.currentModule;
      if (params.currentLesson) state.currentLesson = params.currentLesson;
      if (params.learnerLevel) state.learnerLevel = params.learnerLevel;
      if (params.assessmentSummary)
        state.assessmentSummary = params.assessmentSummary;
      if (params.nextStep) state.nextStep = params.nextStep;
      if (params.action === "save") state.active = false;

      if (
        (params.action === "complete" || params.completedItem) &&
        params.completedItem
      ) {
        if (!state.completed.includes(params.completedItem))
          state.completed.push(params.completedItem);
      }

      if ((params.action === "note" || params.note) && params.note) {
        state.notes.push({ at: new Date().toISOString(), text: params.note });
      }

      await saveState(ctx.cwd, state);
      cachedState = state;
      updateUi(ctx, state);

      return {
        content: [{ type: "text", text: statusLines(state).join("\n") }],
        details: { state },
      };
    },
    renderCall(args, theme) {
      return new Text(
        theme.fg("toolTitle", theme.bold("study_update_progress ")) +
          theme.fg("muted", args.action),
        0,
        0,
      );
    },
    renderResult(result, _options, theme) {
      const text =
        result.content[0]?.type === "text"
          ? result.content[0].text
          : "Study progress updated.";
      return new Text(
        theme.fg("success", "✓ ") + theme.fg("muted", text),
        0,
        0,
      );
    },
  });
}
